spring:
  application:
    name: referral-service
  config:
    import:
      - classpath:application-common.yml

user:
  provider:
    type: local  # ['local', 'remote']
  service:
    baseUrl: http://localhost:8080/api/v1