spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/nft
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none # it will stop creating table automatically

server:
  port: 9092
